services:
  - type: web
    name: anitime-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python anitime.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
